name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # https://github.com/rust-lang/cargo/issues/11014
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  rustfmt:
    runs-on: ubuntu-24.04

    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - uses: actions/checkout@v4

      - run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-24.04

    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - uses: actions/checkout@v4

      - run: cargo +nightly clippy -- --deny warnings
  ci:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

      matrix:
        include:
          - toolchain: stable
          - toolchain: beta
          - toolchain: nightly
          - toolchain: 1.57.0   # MSRV

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test
      - run: cargo test --no-default-features
      - run: cargo test --no-default-features --features=aead
      - run: cargo test --no-default-features --features=ecdsa
      - run: cargo test --no-default-features --features=rsa_sig
